//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int ID { get; set; }
        public string BaseCurrency { get; set; }
        public string ToCurrency { get; set; }
        public decimal Value { get; set; }
        public System.DateTime TimeValue { get; set; }
    }
}
