//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        public int ID { get; set; }
        public string AppID { get; set; }
        public string UserName { get; set; }
        public string TaskName { get; set; }
        public string Prority { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Url { get; set; }
    }
}
